_wandb:
    value:
        cli_version: 0.21.2
        e:
            zltpjd1m7zz0ib4a79jcko7nf998h623:
                args:
                    - --train_data_path
                    - data/tiny_train.txt
                    - --valid_data_path
                    - data/tiny_valid.txt
                    - --max_iters
                    - "5"
                    - --batch_size
                    - "8"
                    - --context_length
                    - "64"
                    - --d_model
                    - "128"
                    - --num_layers
                    - "2"
                    - --run_name
                    - smoke_test
                codePath: cs336_basics/main_train.py
                codePathLocal: main_train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.0"
                disk:
                    /:
                        total: "1081101176832"
                        used: "53976477696"
                email: 2398748524@qq.com
                executable: /home/wcy/cs336_course/assignment1-basics/.venv/bin/python3
                git:
                    commit: 036968efc5195d73fb3ad1be83d488634f6a95d9
                    remote: git@github.com:Elcid-v1/assignment1-basics.git
                gpu: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                      uuid: GPU-6737e668-9489-ac07-be0a-81cfafe290f6
                host: LAPTOP-O4KC17HP
                memory:
                    total: "7199719424"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/wcy/cs336_course/assignment1-basics/cs336_basics/main_train.py
                python: CPython 3.12.9
                root: /home/wcy/cs336_course/assignment1-basics/cs336_basics
                startedAt: "2026-01-30T17:02:46.461666Z"
                writerId: zltpjd1m7zz0ib4a79jcko7nf998h623
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.12.9
            "5": 0.21.2
            "12": 0.21.2
            "13": linux-x86_64
batch_size:
    value: 8
context_length:
    value: 64
d_ff:
    value: 2048
d_model:
    value: 128
device:
    value: cuda
ffn_type:
    value: swiglu
lr:
    value: 0.0006
max_iters:
    value: 5
max_norm:
    value: 1
min_lr:
    value: 6e-05
no_rms_norm:
    value: false
no_rope:
    value: false
norm_mode:
    value: pre
num_heads:
    value: 8
num_layers:
    value: 2
out_dir:
    value: out
run_name:
    value: smoke_test
train_data_path:
    value: data/tiny_train.txt
valid_data_path:
    value: data/tiny_valid.txt
vocab_size:
    value: 10000
warmup_iters:
    value: 1000
